:github-tag: master
:github-repo: spring-cloud/spring-cloud-connectors
:github-raw: http://raw.github.com/{github-repo}/{github-tag}
:github-code: http://github.com/{github-repo}/tree/{github-tag}
:toc:

= Spring Cloud Heroku Connector

[[spring-cloud-connectors-install]]

This connector will discover services bound to an application running in Heroku. It currently knows about:

* PostgreSQL (Heroku)
* MySQL (ClearDB)
* Redis (RedisToGo, Redis Cloud, RedisGreen, openredis)
* MongoDB (MongoLab, MongoHQ, MongoSoup)
* RabbitMQ (CloudAMQP)

Pull requests for adding additional services are welcome.

== Supporting additional providers for existing service types

To add support for discovering a new provider for a service already listed above, add the provider's environment prefix to the list in `getEnvPrefixes()` on the `ServiceInfoCreator` class.

== Supporting new service types

Extend `HerokuServiceInfoCreator` with a creator for <<spring-cloud-core.adoc#_adding_service_discovery,your service's `ServiceInfo` class>>.

Add the fully-qualified class name for your creator to

----
META-INF/service/org.springframework.cloud.heroku.HerokuServiceInfoCreator
----

== Limitations

Unlike CloudFoundry, Heroku exposes very little information about the app that is retrievable from within a running instance. For example, there is no good way to find the name of the application. Therefore, if an app desires such info, it needs to make it available through environment variables.

To have sensible app name available through `ApplicationInstanceInfo`, set the `SPRING_CLOUD_APP_NAME` environment variable

----
heroku config:add SPRING_CLOUD_APP_NAME=myappname --app myappname
----

If this env variable is not set, the app name will be set to `<unknown>`.
