:github-tag: master
:github-repo: spring-cloud/spring-cloud-connectors
:github-raw: http://raw.github.com/{github-repo}/{github-tag}
:github-code: http://github.com/{github-repo}/tree/{github-tag}
:toc: left
:toclevels: 3

= Spring Cloud Connectors

[[spring-cloud-connectors-install]]

== Introduction

Spring Cloud Connectors provides a simple abstraction for JVM-based applications running on cloud platforms to discover bound services and deployment information at runtime, and provides support for registering discovered services as Spring beans. It is based on a plugin model so that the identical compiled application can be deployed locally or on any of multiple cloud platforms, and it supports custom service definitions through Java SPI.

The Connectors project provides out-of-the-box support for discovering common services on Heroku and Cloud Foundry clouds. It also includes a properties-based connector that can supply configuration for development and testing.

=== Concepts

The core Connectors concepts are described below.

[cols="3,7", width="100%"]
|===========================================================================================================================================================================
|**Cloud Connector** |A platform-specific interface that identifies the presence of the platform and discovers any services bound to the application deployment.
|**Service Connector** |An object that represents a runtime connection to a service (for example, a `javax.sql.DataSource`).
|**Service Information** |Information about the underlying service (such as host, port, and credentials).
|**Application Information** |Information about the application and the particular running instance.
|===========================================================================================================================================================================

=== Submodules

The project contains three major submodules.

* **Spring Cloud Connectors Core**: The core library, which is both cloud-agnostic and Spring-agnostic. It provides a programmatic entry point for developers who prefer to access cloud services and application information manually. It also provides basic service definitions for several common services (databases, message queues) and an SPI-based extension mechanism for contributing cloud and service connectors.
* **Spring Cloud Spring Service Connector**: A Spring library that exposes application information, cloud information, and discovered services as Spring beans of the appropriate type (for example, an SQL service will be exposed as a `javax.sql.DataSource` with optional connection pooling).
* The cloud connectors:
 ** **Spring Cloud Cloud Foundry Connector**: Connector for link:http://cloudfoundry.org/[Cloud Foundry].
 ** **Spring Cloud Heroku Connector**: Connector for link:https://www.heroku.com/[Heroku].
 ** **Spring Cloud local-configuration Connector**: Properties-based connector for manually providing configuration information during development or testing. Allows use of the same Spring Cloud configuration wiring in all stages of application deployment.

== Getting Started

See below for examples of how to include the appropriate dependencies using your build system.

=== Including Cloud Connectors

Include the connector for each cloud platform which you want to be discoverable. Including multiple connectors is perfectly fine; each connector will determine whether it should be active in a particular environment.

In Maven, replacing `${VERSION}` with the desired artifact version:

[source,xml]
----
<!-- To use Spring Cloud Connectors for development -->
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-localconfig-connector</artifactId>
    <version>${VERSION}</version>
</dependency>

<!-- If you intend to deploy the app to Cloud Foundry -->
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-cloudfoundry-connector</artifactId>
    <version>${VERSION}</version>
</dependency>

<!-- If you intend to deploy the app to Heroku -->
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-heroku-connector</artifactId>
  <version>${VERSION}</version>
</dependency>
----

In Gradle, replacing `${VERSION}` with the desired version:

[source,groovy]
----
dependencies {

    // to use Spring Cloud Connectors for development
    compile 'org.springframework.cloud:spring-cloud-localconfig-connector:${VERSION}'
    
    // If you intend to deploy the app to Cloud Foundry
    compile 'org.springframework.cloud:spring-cloud-cloudfoundry-connector:${VERSION}'

    // If you intend to deploy the app to Heroku
    compile 'org.springframework.cloud:spring-cloud-heroku-connector:${VERSION}'

}
----

=== Spring Applications

If you're writing a Spring application, include the <<Spring Cloud Spring Service Connector>> dependency in addition to your cloud connector dependencies.

In Maven:

[source,xml]
----
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-spring-service-connector</artifactId>
  <version>${VERSION}</version>
</dependency>
----

In Gradle:

[source,groovy]
----
dependencies {

    compile 'org.springframework.cloud:spring-cloud-spring-service-connector:${VERSION}'

}
----

Then follow the instructions in the <<Spring Cloud Spring Service Connector>> documentation on Spring configuration <<_the_java_configuration,using Java configuration>> or the <<_the_code_cloud_code_namespace,`<cloud>` namespace>>.

=== Non-Spring Applications

The `spring-cloud-core` dependency is included by each cloud connector, so simply include the connectors for the platforms you want. Then follow the <<_spring_cloud_connectors_core,instructions on using the Spring Cloud Connectors API>>.

== Spring Cloud Connectors Core

This core library provides programmatic access to application and service information. This library has no Spring dependencies and may be used in non-Spring applications.

**This library requires Java 6 or newer.** It is cloud-agnostic; using the Java SPI, it supports pluggable cloud and service connectors. Support for Cloud Foundry and Heroku is available out-of-the-box, in addition to locally-provided configuration for development and testing.

=== Connecting to a Cloud

[NOTE]
====
If you are using Spring Cloud in a Spring application, you should consider <<_spring_cloud_spring_service_connector,automatically injecting Spring beans>> instead.
====

* Include the desired cloud connectors on the runtime classpath, <<_getting_started,as described in the main documentation>>.

* Create a `CloudFactory` instance. Creation of a `CloudFactory` instance is a bit expensive, so we recommend using a singleton instance.  If you are using a dependency injection framework such as Spring, create a bean for the `CloudFactory`.
+
[source,java]
----
CloudFactory cloudFactory = new CloudFactory();
----

* Obtain the `Cloud` object for the environment in which the application is running.
+
[source,java]
----
Cloud cloud = cloudFactory.getCloud();
----
+
Note that you must have a `CloudConnector` suitable for your deployment environment on your classpath.  For example, if you are deploying the application to Cloud Foundry, you must add the <<_spring_cloud_cloud_foundry_connector,Cloud Foundry Connector>> to your classpath. If no suitable `CloudConnector` is found, the `getCloud()` method will throw a `CloudException`.

* Use the `Cloud` instance to access application and service information and to create service connectors.
+
[source,java]
----
// ServiceInfo has all the information necessary to connect to the underlying service
List<ServiceInfo> serviceInfos = cloud.getServiceInfos();
----
+
[source,java]
----
// Find the `ServiceInfo` definitions suitable for connecting to a particular service type
List<ServiceInfo> databaseInfos = cloud.getServiceInfos(DataSource.class);
----
+
[source,java]
----
// Alternatively, let Spring Cloud create a service connector for you
String serviceId = "inventory-db";
DataSource ds = cloud.getServiceConnector(serviceId, DataSource.class,
                                            null /* default config */);
----

=== Adding Cloud Connectors

A cloud provider may extend Spring Cloud to make it work with a new cloud platform by adding a new `CloudConnector`. The connector is responsible for determining whether the application is running in the specific cloud, identifying application information (such as the name and instance ID of the particular running instance), and mapping bound services (such as URIs exposed in environment variables) as `ServiceInfo` objects.

[TIP]
====
See the <<_spring_cloud_cloud_foundry_connector,Cloud Foundry Connector>> and <<_spring_cloud_heroku_connector,Heroku Connector>> for examples.
====

Spring Cloud uses the Java SPI to discover available connectors. New cloud connectors should list the fully-qualified class name in the provider-configuration file at `META-INF/services/org.springframework.cloud.CloudConnector`.

=== Adding Service Discovery

To allow Spring Cloud to discover a new type of service (e.g. a `HelloWorldService`), create a `ServiceInfo` class containing the information necessary to connect to the service. If your service can be specified via a URI, extend `UriBasedServiceInfo` and provide the URI scheme in a call to the `super` constructor.

The following class will expose information for a service available at `helloworld://username:password@host:port/Bonjour`.

[source,java]
----
public class HelloWorldServiceInfo extends UriBasedServiceInfo {
    public static final String URI_SCHEME = "helloworld";

  // Needed to support structured service definitions such as Cloud Foundry's
    public HelloWorldServiceInfo(String id, String host, int port, String username, String password, String greeting) {
    super(id, URI_SCHEME, host, port, username, password, greeting);
    }

    // Needed to support URI-based service definitions such as Heroku's
    public HelloWorldServiceInfo(String id, String uri) {
        super(id, uri);
    }
}
----

After creating the `ServiceInfo` class, you will need to create a `ServiceInfoCreator` for each cloud platform you want to support.  You will probably want to extend the appropriate creator base class(es), such as `HerokuServiceInfoCreator`. This is often as simple as writing a method that (in the case of the `HelloWorldService`) instantiates a new `HelloWorldServiceInfo`.

Register your `ServiceInfoCreator` classes in the appropriate provider-configuration file for your cloud's `ServiceInfoCreator` base class.

=== Adding Service Connectors

A service connector consumes a `ServiceInfo` discovered by the cloud connector and converts it into the appropriate service object, such as a `DataSource` in the case of a service definition that represents a SQL database.

Service connectors may be tightly bound to the framework whose service objects they are creating. For example, some connectors in the <<_spring_cloud_spring_service_connector,Spring Service Connector>> create connection factories defined by Spring Data, for use in building Spring Data templates.

To add new service connectors, implement `ServiceConnectorCreator` in your connector classes and list the fully-qualified class names in the provider-configuration file at `META-INF/services/org.springframework.cloud.service.ServiceConnectorCreator`.

== Spring Cloud Spring Service Connector

This library provides `ServiceConnectorCreator` implementations for `javax.sql.DataSource` and various link:http://projects.spring.io/spring-data/[Spring Data] connector factories. It also provides Java configuration and XML namespace support for connecting to cloud services, accessing cloud services, and accessing application properties.

=== The Java Configuration

Typical use of the Java configuration involves extending the `AbstractCloudConfig` class and creating beans for services by annotating methods with the `@Bean` annotation. (If you are migrating an application that uses link:https://spring.io/blog/2011/11/04/using-cloud-foundry-services-with-spring-part-2-auto-reconfiguration/[auto-reconfiguration], you might first try the <<_scanning_for_services,service-scanning approach>> until you need more explicit control.) The Spring Service Connector Java configuration also offers a way to expose application and service properties in case you want lower-level access when creating your own service connectors (or for debugging purposes, etc.).  

==== Creating Service Beans

The configuration shown in the following example creates a `DataSource` bean that connects to the only relational database service bound to the application (it will fail if there is no such unique service).  It also creates a `MongoDbFactory` bean, which again connects to the only MongoDB service bound to the application. (For ways to connect to other services, see the link:http://docs.spring.io/autorepo/docs/spring-cloud/current/api/org/springframework/cloud/config/java/AbstractCloudConfig.html[Javadoc for `AbstractCloudConfig`].)

[source,java]
----
class CloudConfig extends AbstractCloudConfig {
    @Bean
        public DataSource inventoryDataSource() {
            return connectionFactory().dataSource();
        }
    
    @Bean
    public MongoDbFactory documentMongoDbFactory() {
        return connectionFactory().mongoDbFactory();
    }
    
    // (More beans to obtain service connectors)
}
----

You can specify a bean name by providing a value in the `@Bean` annotation.

[source,java]
----
@Bean("inventory-service")
----

Otherwise, bean names will match the method names. (This works in the same way as does Spring's Java configuration.)
    
If you have more than one service of a type bound to the application or want explicit control over the services to which a bean is bound, you can pass the service names to methods such as `dataSource()` and `mongoDbFactory()`.
    
[source,java]
----
class CloudConfig extends AbstractCloudConfig {
    @Bean
    public DataSource inventoryDataSource() {
        return connectionFactory().dataSource("inventory-db-service");
    }

    @Bean
    public MongoDbFactory documentMongoDbFactory() {
        return connectionFactory().mongoDbFactory("document-service");
    }

    // (More beans to obtain service connectors)
}
----
 
Methods such as `dataSource()` come in additional overloaded variants that let you specify configuration options (such as pooling parameters). See the relevant Javadocs for more information.

==== Connecting to Generic Services

The Java configuration supports access to generic services (services which don't have a directly mapped method; this is typical for a newly-introduced service or when connecting to a private service in a private PaaS) through the `service()` method. It follows the same pattern as `dataSource()` etc.,whico except that it allows you to supply the connector type as an additional parameter.

==== Scanning for Services

You can scan for each bound service using the `@ServiceScan` annotation. (This is conceptually similar to Spring's `@ComponentScan` annotation.)

[source,java]
----
@Configuration
@ServiceScan
class CloudConfig {
}
----
    
In the above example, the configuration will create one bean of the appropriate type (such as a `DataSource` in the case of a relational database service). Each bean will have an `id` matching the corresponding service name.

You can inject such beans using autowiring.

[source,java]
----
@Autowired DataSource inventoryDb;
----

If the application is bound to more than one service of a given type, you can specify one by using the `@Qualifier` annotation and providing it with the name of the appropriate service.

[source,java]
----
@Autowired @Qualifier("inventory-db") DataSource inventoryDb;
@Autowired @Qualifier("shipping-db") DataSource shippingDb;
----

==== Accessing Service Properties

You can expose raw properties for all services and for the application through a bean.

[source,java]
----
class CloudPropertiesConfig extends AbstractCloudConfig {
    @Bean
    public Properties cloudProperties() {
        return properties();
    }
}
----

=== The `<cloud>` Namespace

==== Setting Up

The `<cloud>` namespace offers a simple way for a Spring application to connect to cloud services.

To use this namespace, add a declaration for it.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:cloud="http://www.springframework.org/schema/cloud"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.springframework.org/schema/cloud http://www.springframework.org/schema/cloud/spring-cloud.xsd">

<!-- <cloud> namespace usage here -->
----

==== Creating Service Beans

A namespace element which creates a service bean conforms to the following pattern (in this example, the bean is for a relational database service).

[source,xml]
----
<cloud:data-source id="inventory-db" service-name="inventory-db-service">
    <cloud:connection properties="sessionVariables=sql_mode='ANSI';characterEncoding=UTF-8"/>
    <cloud:pool pool-size="20" max-wait-time="200"/>
</cloud>
----

The above example creates a `javax.sql.DataSource` bean with the id `inventory-db`. The bean is bound to the `inventory-db-service` and is configured with the `connection` and `pool` properties specified in the nested `<cloud:connection>` and `<cloud:pool>` elements.

If no `id` attribute is specified, the `id` is set to the service name. If no `service-name` is specified, the bean is bound to the only service in the corresponding category (in this case, a relational database). If no unique service is found, a runtime exception will be thrown.

Other namespace elements which create service connectors include:

[source,xml]
----
<cloud:mongo-db-factory/>
<cloud:redis-connection-factory/>
<cloud:rabbit-connection-factory/>
----

==== Connecting to Generic Services

Spring Service Connector also supports a generic `<cloud:service>` namespace for connecting to a service with no directly-mapped element (this is typical for a newly-introduced service or when connecting to a private service in a private PaaS). You must specify either the `connector-type` attribute (for locating a unique service by type) or the `service-name` attribute.

[source,xml]
----
 <cloud:service id="email" service-name="email-service" connector-type="com.something.EmailConnectory" />
----

==== Scanning for Services

Besides these elements (which create only one bean per element), Spring Service Connector provides a `<cloud:service-scan>` element, in the same spirit as the `<context:component-scan>` element. It scans for all services bound to the application and creates a bean for each service. Each bean has an `id` matching the service name; this means that you can use the `@Qualifier` annotation along with `@Autowired` when there is more than one bean of the same type.

==== Accessing Service Properties

Lastly, Spring Service Connector provides a `<cloud:properties>` element, which exposes properties for the application and for services.

== Spring Cloud Cloud Foundry Connector

See <<spring-cloud-cloud-foundry-connector.adoc#,Spring Cloud Cloud Foundry Connector>>.

== Spring Cloud Heroku Connector

See <<spring-cloud-heroku-connector.adoc#,Spring Cloud Heroku Connector>>.

== Spring Cloud local-configuration Connector

This connector provides the ability to configure Spring Cloud services locally for development or testing. **The current implementation reads from Java properties only.**

=== Quick Start

Since service URIs contain passwords and should not be stored in code, this connector does not attempt to read service definitions out of the classpath. You can provide service definitions as system properties.

[source,term]
----
java -Dspring.cloud.database='mysql://user:pass@host:1234/dbname' -jar my-app.jar
----

You can also provide service definitions from a configuration properties file, either by setting the `spring.cloud.propertiesFile` system property:

[source,term]
----
java -Dspring.cloud.propertiesFile=/path/to/spring-cloud.properties -jar my-app.jar
----

or by providing the bootstrap properties file `spring-cloud-bootstrap.properties` on the runtime classpath. This file will be inspected only for the property named `spring.cloud.propertiesFile`, and its value will be interpolated from the system properties.

[source,properties]
----
spring.cloud.propertiesFile: ${user.home}/.config/myApp/spring-cloud.properties
----

The system properties, or the configuration properties file, should contain an application ID and the desired services in the following format.

[source,properties]
----
spring.cloud.appId:    myApp
; spring.cloud.{id}:   URI
spring.cloud.database: mysql://user:pass@host:1234/dbname
----

The service type is determined by the URI scheme. The connector will activate if it finds a property (either in the system properties or in the configuration properties file) named `spring.cloud.appId`.

=== Property Sources

This connector first attempts to read the system properties generally and a system property named `spring.cloud.propertiesFile` specifically. If the system properties are not readable (if the security manager denies `checkPropertiesAccess`), then they will be treated as empty.  If a system property named `spring.cloud.propertiesFile` is found, then that file will be loaded as a property list.

==== Providing a Bootstrap Properties File

To avoid having to manually configure run configurations or test runners with the path to the configuration properties file, the connector can read a templated filename out of the runtime classpath. This file must be named `spring-cloud-bootstrap.properties` and be located at the classpath root. For security, the connector will not attempt to read any service URIs out of the file. If the connector does find the file, it will read the property `spring.cloud.propertiesFile` and link:http://commons.apache.org/proper/commons-lang/javadocs/api-release/index.html?org/apache/commons/lang3/text/StrSubstitutor.html[substitute the pattern `${system.property}`] with the appropriate value from the system properties. The most useful option is generally `${user.home}`.

A configuration properties file specified in the system properties will override any bootstrap file that may be available on the classpath.

==== Property Precedence

To provide the maximum configuration flexibility, the connector will override any properties (both application ID and service definitions) specified in the file at `spring.cloud.propertiesFile` with system properties defined at runtime. The connector will log a message at `WARN` if you override a service ID.

=== Activating the Connector

Spring Cloud Core expects exactly one cloud connector to match the runtime environment.  This connector identifies the &#8220;local cloud&#8221; by the presence of a property, in a configuration properties file or in the system properties, named `spring.cloud.appId`. This property will be used in the `ApplicationInstanceInfo`.

=== Service Definitions

If the connector is activated, it will iterate through all of the available properties for keys matching the pattern `spring.cloud.{serviceId}`. Each value is interpreted as a URI to a service, and the type of service is determined from the scheme. Every standard `UriBasedServiceInfo` is supported.

=== Supporting Additional Services

Extend `LocalConfigServiceInfoCreator` with a creator for <<_adding_service_discovery,your service's `ServiceInfo` class>>.

Add the fully-qualified class name for your creator to `META-INF/service/org.springframework.cloud.localconfig.LocalConfigServiceInfoCreator`.

=== Instance ID

This connector creates a UUID for use as the instance ID, as Java does not provide any portable mechanism for reliably determining hostnames or PIDs.

== Extending Spring Cloud Connectors

Coming soon...

